const heroSize = 50;
const obstacleSize = 25;
const heroSpeed = 20;
const obstacleSpeed = 1;
const pfandValue = 0.25;
const obstacleValue =-0.5;
let startGame = false;
let gameOver = false;
let gameWon = false;